version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-server-2.517-jdk21
    container_name: jenkins-server
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8081:8080"
      - "50001:50000"
    
